version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=https://n8n.YOUR_DOMAIN.com  # opcional si usás subdominios
    volumes:
      - n8n_data:/home/node/.n8n

  appsmith:
    image: appsmith/appsmith-ce
    restart: always
    ports:
      - "8080:80"
    volumes:
      - appsmith_stacks:/appsmith-stacks

volumes:
  n8n_data:
  appsmith_stacks:
